# Generated by Django 5.1.4 on 2026-09-22 05:24

import apps.bookings.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('direct', 'Directed at one provider'), ('broadcast', 'Broadcast to the area')], default='broadcast', max_length=20)),
                ('preferred_start', models.DateTimeField()),
                ('preferred_end', models.DateTimeField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn by customer'), ('expired', 'Expired unanswered')], db_index=True, default='open', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='accounts.customerprofile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalogue.location')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='catalogue.service')),
                ('target_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_requests', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.bookings.models.request_photo_path)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('response_seconds', models.PositiveIntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_responses', to='accounts.providerprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bookings.servicerequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('awaiting_confirm', 'Awaiting confirmation'), ('completed', 'Completed'), ('cancelled_customer', 'Cancelled by customer'), ('cancelled_provider', 'Cancelled by provider'), ('disputed', 'Disputed')], db_index=True, default='scheduled', max_length=30)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('customer_confirmed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('customer_confirmed_cancellation', models.BooleanField(default=False)),
                ('was_no_show', models.BooleanField(default=False)),
                ('auto_confirmed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.customerprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.providerprofile')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(blank=True, max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('actor', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookings.booking')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='bookings_bo_booking_d5ff0d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['state', 'expires_at'], name='bookings_se_state_5be017_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_se_custome_4c5aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['service', 'location', 'state'], name='bookings_se_service_b86ce5_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_end__gt', models.F('preferred_start'))), name='request_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'broadcast'), ('target_provider__isnull', False), _connector='OR'), name='direct_request_needs_target'),
        ),
        migrations.AddIndex(
            model_name='providerresponse',
            index=models.Index(fields=['provider', '-created_at'], name='bookings_pr_provide_ba7b4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerresponse',
            constraint=models.UniqueConstraint(fields=('request', 'provider'), name='one_response_per_provider_per_request'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider', 'state'], name='bookings_bo_provide_11a353_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer', '-created_at'], name='bookings_bo_custome_10bd54_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['state', 'completed_at'], name='bookings_bo_state_cf89eb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['state', 'scheduled_for'], name='bookings_bo_state_5a1582_idx'),
        ),
    ]
