# Generated by Django 5.1.4 on 2026-09-25 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_affected', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['job', '-started_at'], name='operations__job_6bf35e_idx'), models.Index(fields=['job', 'status', '-started_at'], name='operations__job_39a5d4_idx')],
            },
        ),
    ]
