"""Catalogue model behaviour: constraints, slugs, tree walking, price bands."""

from decimal import Decimal

import pytest
from django.db import IntegrityError, transaction

from apps.catalogue.models import Location, Service, ServiceCategory

pytestmark = pytest.mark.django_db


@pytest.fixture
def category():
    return ServiceCategory.objects.create(name="Electrical")


@pytest.fixture
def dhaka():
    return Location.objects.create(name="Dhaka", level=Location.Level.CITY,
                                   latitude=Decimal("23.8103"),
                                   longitude=Decimal("90.4125"))


# ------------------------------------------------------------------- slugs
def test_category_slug_autogenerated(category):
    assert category.slug == "electrical"


def test_service_slug_autogenerated(category):
    service = Service.objects.create(category=category,
                                     name="Ceiling fan installation")
    assert service.slug == "ceiling-fan-installation"


def test_same_service_slug_allowed_in_different_categories(category):
    other = ServiceCategory.objects.create(name="AC & Refrigeration")
    Service.objects.create(category=category, name="Repair")
    # Must not collide -- "Repair" is a reasonable name under many categories.
    Service.objects.create(category=other, name="Repair")
    assert Service.objects.filter(slug="repair").count() == 2


def test_duplicate_service_slug_within_category_rejected(category):
    Service.objects.create(category=category, name="Repair")
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            Service.objects.create(category=category, name="Repair")


# ------------------------------------------------------------- constraints
def test_price_band_must_be_ordered(category):
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            Service.objects.create(
                category=category, name="Broken band",
                suggested_price_min=Decimal("2000"),
                suggested_price_max=Decimal("500"),
            )


def test_open_ended_band_is_allowed(category):
    """visit_quote services legitimately have no band."""
    service = Service.objects.create(
        category=category, name="House wiring",
        pricing_model=Service.PricingModel.VISIT_QUOTE,
    )
    assert service.price_flag(Decimal("5000")) is None


def test_non_city_location_requires_parent():
    with pytest.raises(IntegrityError):
        with transaction.atomic():
            Location.objects.create(name="Orphan thana",
                                    level=Location.Level.THANA)


def test_city_may_have_no_parent(dhaka):
    assert dhaka.parent is None


# ------------------------------------------------------------- price flags
@pytest.mark.parametrize("price,expected", [
    (Decimal("300"), "low"),
    (Decimal("500"), "normal"),
    (Decimal("900"), "normal"),
    (Decimal("1200"), "normal"),
    (Decimal("1500"), "high"),
])
def test_price_flag_classifies_against_band(category, price, expected):
    service = Service.objects.create(
        category=category, name="Fan installation",
        suggested_price_min=Decimal("500"),
        suggested_price_max=Decimal("1200"),
    )
    assert service.price_flag(price) == expected


# -------------------------------------------------------------- tree walks
def test_descendant_ids_expands_downward(dhaka):
    """
    A provider serving a thana must match a request in any area inside it,
    which is what provider search relies on in M5.
    """
    thana = Location.objects.create(name="Dhanmondi",
                                    level=Location.Level.THANA, parent=dhaka)
    area_a = Location.objects.create(name="Dhanmondi 27",
                                     level=Location.Level.AREA, parent=thana)
    area_b = Location.objects.create(name="Jigatola",
                                     level=Location.Level.AREA, parent=thana)

    ids = thana.descendant_ids()
    assert set(ids) == {thana.pk, area_a.pk, area_b.pk}


def test_descendant_ids_of_leaf_is_itself(dhaka):
    thana = Location.objects.create(name="Gulshan",
                                    level=Location.Level.THANA, parent=dhaka)
    assert thana.descendant_ids() == [thana.pk]


def test_city_descendants_cover_whole_tree(dhaka):
    thana = Location.objects.create(name="Mirpur",
                                    level=Location.Level.THANA, parent=dhaka)
    area = Location.objects.create(name="Mirpur 10",
                                   level=Location.Level.AREA, parent=thana)
    assert set(dhaka.descendant_ids()) == {dhaka.pk, thana.pk, area.pk}


def test_ancestors_are_root_first(dhaka):
    thana = Location.objects.create(name="Uttara",
                                    level=Location.Level.THANA, parent=dhaka)
    area = Location.objects.create(name="Sector 7",
                                   level=Location.Level.AREA, parent=thana)
    assert area.ancestors() == [dhaka, thana]


def test_str_includes_parent_for_readability(dhaka):
    thana = Location.objects.create(name="Banani",
                                    level=Location.Level.THANA, parent=dhaka)
    assert str(thana) == "Banani, Dhaka"
    assert str(dhaka) == "Dhaka"


# ----------------------------------------------------------------- deletion
def test_category_with_services_cannot_be_deleted(category):
    """PROTECT: deleting a category must not silently destroy its services."""
    Service.objects.create(category=category, name="Fan installation")
    from django.db.models import ProtectedError
    with pytest.raises(ProtectedError):
        category.delete()


def test_location_with_children_cannot_be_deleted(dhaka):
    Location.objects.create(name="Dhanmondi", level=Location.Level.THANA,
                            parent=dhaka)
    from django.db.models import ProtectedError
    with pytest.raises(ProtectedError):
        dhaka.delete()
