# Generated by Django 5.1.4 on 2026-09-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tier', models.CharField(max_length=20)),
                ('factors', models.JSONField()),
                ('algo_version', models.CharField(max_length=10)),
                ('trigger', models.CharField(choices=[('booking_completed', 'Booking completed'), ('booking_cancelled', 'Booking cancelled'), ('review_changed', 'Review created or changed'), ('verification_decided', 'Verification decided'), ('dispute_changed', 'Dispute opened or resolved'), ('nightly_batch', 'Nightly batch'), ('manual', 'Manual recomputation')], max_length=40)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='trust_trust_provide_d2925f_idx'), models.Index(fields=['algo_version'], name='trust_trust_algo_ve_675253_idx')],
            },
        ),
    ]
