# Generated by Django 5.1.4 on 2026-09-20 15:52

import apps.providers.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name_plural': 'availability',
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['provider', 'weekday'], name='providers_a_provide_4d073d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'), models.UniqueConstraint(fields=('provider', 'weekday', 'start_time'), name='availability_window_unique')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['provider', 'date'], name='providers_a_provide_b6f0fa_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'date'), name='availability_exception_unique_per_day'), models.CheckConstraint(condition=models.Q(('is_available', False), models.Q(('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR'), name='availability_exception_hours_required_when_available')],
            },
        ),
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='accounts.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_offerings', to='catalogue.service')),
            ],
            options={
                'verbose_name': 'provider service',
                'ordering': ['service__category__display_order', 'service__name'],
                'indexes': [models.Index(fields=['service', 'is_active'], name='providers_p_service_ea83a3_idx'), models.Index(fields=['provider', 'is_active'], name='providers_p_provide_ef492f_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'service'), name='provider_service_unique')],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='catalogue.location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'service area',
                'ordering': ['location__name'],
                'indexes': [models.Index(fields=['location', 'provider'], name='providers_s_locatio_13e7e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'location'), name='provider_location_unique')],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('nid_front', 'NID front'), ('nid_back', 'NID back'), ('trade_certificate', 'Trade certificate'), ('address_proof', 'Address proof')], max_length=30)),
                ('file', models.FileField(upload_to=apps.providers.models.verification_document_path)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='accounts.providerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='providers_v_status_7bf1a1_idx'), models.Index(fields=['provider', 'document_type'], name='providers_v_provide_74805e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.providers.models.work_photo_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['provider', 'display_order'], name='providers_w_provide_814eff_idx')],
            },
        ),
    ]
