# Generated by Django 5.1.4 on 2026-09-21 12:39

import apps.common.storage
import apps.providers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(storage=apps.common.storage.PrivateMediaStorage(), upload_to=apps.providers.models.verification_document_path),
        ),
    ]
