# Generated by Django 5.2.17 on 2026-09-25 17:50

import apps.common.storage
import apps.providers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_verificationdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(storage=apps.common.storage.private_storage, upload_to=apps.providers.models.verification_document_path),
        ),
    ]
