# Generated by Django 5.1.4 on 2026-09-20 08:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='catalogue_s_is_acti_2bd2d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('level', models.CharField(choices=[('city', 'City'), ('thana', 'Thana'), ('area', 'Area')], max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalogue.location')),
            ],
            options={
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level', 'is_active'], name='catalogue_l_level_87c5c7_idx'), models.Index(fields=['parent', 'is_active'], name='catalogue_l_parent__b1268b_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'slug'), name='location_slug_unique_in_parent'), models.CheckConstraint(condition=models.Q(('level', 'city'), ('parent__isnull', False), _connector='OR'), name='location_non_city_requires_parent')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('pricing_model', models.CharField(choices=[('fixed', 'Fixed price'), ('hourly', 'Hourly rate'), ('visit_quote', 'Visit fee, then quote')], default='fixed', max_length=20)),
                ('suggested_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('suggested_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('typical_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalogue.servicecategory')),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalogue_s_categor_8778b4_idx'), models.Index(fields=['is_active', 'display_order'], name='catalogue_s_is_acti_e23260_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='service_slug_unique_in_category'), models.CheckConstraint(condition=models.Q(('suggested_price_min__isnull', True), ('suggested_price_max__isnull', True), ('suggested_price_max__gte', models.F('suggested_price_min')), _connector='OR'), name='service_price_band_ordered')],
            },
        ),
    ]
