# Generated by Django 5.2.17 on 2026-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='search_terms',
            field=models.TextField(blank=True, help_text='Words customers use for this job, comma separated, so search matches symptoms and not only the official name.'),
        ),
    ]
